const styles = {
  available: {
    backgroundColor: '#fff',
    padding: 2,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    color: 'black',
    height: 90,
    borderRadius: 5,
    boxShadow: 'none',
    fontWeight: 600,
    fontSize: 19,
    cursor: 'pointer',
  },
  booked: {
    backgroundColor: '#f5f5f5',
    padding: 2,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    color: '#b2bfd2',
    height: 90,
    borderRadius: 5,
    boxShadow: 'none',
    fontWeight: 600,
    fontSize: 19,
  },
  choose: {
    backgroundColor: '#3178F6',
    padding: 2,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    color: 'white',
    height: 90,
    borderRadius: 5,
    boxShadow: 'none',
    fontWeight: 600,
    fontSize: 19,
    cursor: 'pointer',
  },
};

export default styles;
